### ISSUE TITLE
Desenvolver os dashboards utilizando Python

### ISSUE THREAD

**Issue by estevam5s** [Laboratorio-de-transformacao-Digital/grupo-python#1]
# Gráficos para essa tarefa

1. Utilizar o ``histograma``
2. Utilizar o ``pizza`` (**Homem e mulher**)
3. Utilizar o ``barras simples``

**Comment by Enzo-Zanatta** [comment]
https://colab.research.google.com/drive/1vYiwvP4hJvnpDQnWly6hX84WHTyRC3ev?usp=sharing

Versão mais recente e estável do meu projeto.
